### ISSUE TITLE
升级fastapi版本不然会报错

### ISSUE THREAD

**Issue by Socratea** [PY-GZKY/moyu#1]
jinja2 报错
我升级到了fastapi==0.75.0

**Comment by PY-GZKY** [comment]
你好, 具体报的是什么错误呢, 测试 `fastapi 0.49` 以上版本应该是没问题的

**Comment by Socratea** [comment]
Python版本是 3.9.9，可能是因为这个

**Comment by PY-GZKY** [comment]
OK, 那我先关闭这个 issues
